//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneGraphPlus.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int MruSize {
            get {
                return ((int)(this["MruSize"]));
            }
            set {
                this["MruSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumOrchid")]
        public string MmatBlockColour {
            get {
                return ((string)(this["MmatBlockColour"]));
            }
            set {
                this["MmatBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RoyalBlue")]
        public string CresBlockColour {
            get {
                return ((string)(this["CresBlockColour"]));
            }
            set {
                this["CresBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GreenYellow")]
        public string ShpeBlockColour {
            get {
                return ((string)(this["ShpeBlockColour"]));
            }
            set {
                this["ShpeBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public string GmndBlockColour {
            get {
                return ((string)(this["GmndBlockColour"]));
            }
            set {
                this["GmndBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thistle")]
        public string GmdcBlockColour {
            get {
                return ((string)(this["GmdcBlockColour"]));
            }
            set {
                this["GmdcBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Orange")]
        public string TxmtBlockColour {
            get {
                return ((string)(this["TxmtBlockColour"]));
            }
            set {
                this["TxmtBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumVioletRed")]
        public string TxtrBlockColour {
            get {
                return ((string)(this["TxtrBlockColour"]));
            }
            set {
                this["TxtrBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumPurple")]
        public string GzpsBlockColour {
            get {
                return ((string)(this["GzpsBlockColour"]));
            }
            set {
                this["GzpsBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ColumnGap {
            get {
                return ((int)(this["ColumnGap"]));
            }
            set {
                this["ColumnGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int RowGap {
            get {
                return ((int)(this["RowGap"]));
            }
            set {
                this["RowGap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MmatRow {
            get {
                return ((int)(this["MmatRow"]));
            }
            set {
                this["MmatRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CresRow {
            get {
                return ((int)(this["CresRow"]));
            }
            set {
                this["CresRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ShpeRow {
            get {
                return ((int)(this["ShpeRow"]));
            }
            set {
                this["ShpeRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GmndRow {
            get {
                return ((int)(this["GmndRow"]));
            }
            set {
                this["GmndRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int GmdcRow {
            get {
                return ((int)(this["GmdcRow"]));
            }
            set {
                this["GmdcRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TxmtRow {
            get {
                return ((int)(this["TxmtRow"]));
            }
            set {
                this["TxmtRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int TxtrRow {
            get {
                return ((int)(this["TxtrRow"]));
            }
            set {
                this["TxtrRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GzpsRow {
            get {
                return ((int)(this["GzpsRow"]));
            }
            set {
                this["GzpsRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int BlockWidth {
            get {
                return ((int)(this["BlockWidth"]));
            }
            set {
                this["BlockWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int BlockHeight {
            get {
                return ((int)(this["BlockHeight"]));
            }
            set {
                this["BlockHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int OverflowRow {
            get {
                return ((int)(this["OverflowRow"]));
            }
            set {
                this["OverflowRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string BadTgirColour {
            get {
                return ((string)(this["BadTgirColour"]));
            }
            set {
                this["BadTgirColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimGray")]
        public string ConnectorColour {
            get {
                return ((string)(this["ConnectorColour"]));
            }
            set {
                this["ConnectorColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SaddleBrown")]
        public string MultiConnectorColour {
            get {
                return ((string)(this["MultiConnectorColour"]));
            }
            set {
                this["MultiConnectorColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ConnectorWidth {
            get {
                return ((int)(this["ConnectorWidth"]));
            }
            set {
                this["ConnectorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int MultiConnectorWidth {
            get {
                return ((int)(this["MultiConnectorWidth"]));
            }
            set {
                this["MultiConnectorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public string ConnectorHighlightColour {
            get {
                return ((string)(this["ConnectorHighlightColour"]));
            }
            set {
                this["ConnectorHighlightColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ConnectorHighlightWidth {
            get {
                return ((int)(this["ConnectorHighlightWidth"]));
            }
            set {
                this["ConnectorHighlightWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ConnectorDetectWidth {
            get {
                return ((int)(this["ConnectorDetectWidth"]));
            }
            set {
                this["ConnectorDetectWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSlateGray")]
        public string ConnectorPopupTextColour {
            get {
                return ((string)(this["ConnectorPopupTextColour"]));
            }
            set {
                this["ConnectorPopupTextColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AliceBlue")]
        public string ConnectorPopupBackColour {
            get {
                return ((string)(this["ConnectorPopupBackColour"]));
            }
            set {
                this["ConnectorPopupBackColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public string MissingBlockColour {
            get {
                return ((string)(this["MissingBlockColour"]));
            }
            set {
                this["MissingBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSalmon")]
        public string CloneBlockColour {
            get {
                return ((string)(this["CloneBlockColour"]));
            }
            set {
                this["CloneBlockColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public string MaxisBlockColour {
            get {
                return ((string)(this["MaxisBlockColour"]));
            }
            set {
                this["MaxisBlockColour"] = value;
            }
        }
    }
}
