//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sims2Tools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Double Deluxe\\" +
            "Base")]
        public string Sims2Path {
            get {
                return ((string)(this["Sims2Path"]));
            }
            set {
                this["Sims2Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\University Lif" +
            "e\\EP1")]
        public string Sims2EP1Path {
            get {
                return ((string)(this["Sims2EP1Path"]));
            }
            set {
                this["Sims2EP1Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Double Deluxe\\" +
            "EP2")]
        public string Sims2EP2Path {
            get {
                return ((string)(this["Sims2EP2Path"]));
            }
            set {
                this["Sims2EP2Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Best of Busine" +
            "ss\\EP3")]
        public string Sims2EP3Path {
            get {
                return ((string)(this["Sims2EP3Path"]));
            }
            set {
                this["Sims2EP3Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Fun with Pets\\" +
            "EP4")]
        public string Sims2EP4Path {
            get {
                return ((string)(this["Sims2EP4Path"]));
            }
            set {
                this["Sims2EP4Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Seasons")]
        public string Sims2EP5Path {
            get {
                return ((string)(this["Sims2EP5Path"]));
            }
            set {
                this["Sims2EP5Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Bon Voyage")]
        public string Sims2EP6Path {
            get {
                return ((string)(this["Sims2EP6Path"]));
            }
            set {
                this["Sims2EP6Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Free Time")]
        public string Sims2EP7Path {
            get {
                return ((string)(this["Sims2EP7Path"]));
            }
            set {
                this["Sims2EP7Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Apartment Life" +
            "")]
        public string Sims2EP8Path {
            get {
                return ((string)(this["Sims2EP8Path"]));
            }
            set {
                this["Sims2EP8Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Fun with Pets\\" +
            "SP9")]
        public string Sims2EP9Path {
            get {
                return ((string)(this["Sims2EP9Path"]));
            }
            set {
                this["Sims2EP9Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Fun with Pets\\" +
            "SP1")]
        public string Sims2SP1Path {
            get {
                return ((string)(this["Sims2SP1Path"]));
            }
            set {
                this["Sims2SP1Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Glamour Life S" +
            "tuff")]
        public string Sims2SP2Path {
            get {
                return ((string)(this["Sims2SP2Path"]));
            }
            set {
                this["Sims2SP2Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Double Deluxe\\" +
            "SP4")]
        public string Sims2SP4Path {
            get {
                return ((string)(this["Sims2SP4Path"]));
            }
            set {
                this["Sims2SP4Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Best of Busine" +
            "ss\\SP5")]
        public string Sims2SP5Path {
            get {
                return ((string)(this["Sims2SP5Path"]));
            }
            set {
                this["Sims2SP5Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\University Lif" +
            "e\\SP6")]
        public string Sims2SP6Path {
            get {
                return ((string)(this["Sims2SP6Path"]));
            }
            set {
                this["Sims2SP6Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Best of Busine" +
            "ss\\SP7")]
        public string Sims2SP7Path {
            get {
                return ((string)(this["Sims2SP7Path"]));
            }
            set {
                this["Sims2SP7Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\University Lif" +
            "e\\SP8")]
        public string Sims2SP8Path {
            get {
                return ((string)(this["Sims2SP8Path"]));
            }
            set {
                this["Sims2SP8Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\Origin Games\\The Sims 2 Ultimate Collection\\Double Deluxe\\" +
            "EP99")]
        public string Sims2SCPath {
            get {
                return ((string)(this["Sims2SCPath"]));
            }
            set {
                this["Sims2SCPath"] = value;
            }
        }
    }
}
